//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAamdhani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string ClientKey { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Phone { get; set; }
        public string AddressJson { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string BillingAddress { get; set; }
        public string Shipping { get; set; }
    }
}
