//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAamdhani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTab
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SubMenuId { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public Nullable<int> MenuType { get; set; }
        public Nullable<int> Order { get; set; }
        public string Roles { get; set; }
        public bool ViewInRights { get; set; }
        public bool IsActive { get; set; }
    }
}
