//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAamdhani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string Shipping_Address { get; set; }
        public string BillingAddress { get; set; }
        public Nullable<long> Pincode { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string CancelReason { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PaymentType { get; set; }
    }
}
