//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAamdhani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> MinOrder { get; set; }
        public Nullable<decimal> PricePerPiece { get; set; }
        public Nullable<decimal> MRPPerPiece { get; set; }
        public Nullable<int> AvailableQty { get; set; }
        public string SKUId { get; set; }
        public string HSNCode { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<System.Guid> UniqueId { get; set; }
        public Nullable<int> FabricId { get; set; }
        public Nullable<int> PatternId { get; set; }
        public Nullable<int> StyleId { get; set; }
        public Nullable<int> SareeBorderId { get; set; }
        public Nullable<bool> BlousePiece { get; set; }
        public string SareeLength { get; set; }
        public string Occasion { get; set; }
        public string PackagingType { get; set; }
    }
}
